# -*- coding: utf-8 -*-
"""cv lab 4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15XDRuT5u5RMFA65Bco4QGOrFoUSy2Wt6
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

#function to display images
def show_comparison(original,sobel,prewitt,canny):
  plt.figure(figsize=(12,10))

  #original image
  plt.subplot(2,2,1)
  plt.imshow(original,cmap='gray')
  plt.title('Original grayscale Image')
  plt.axis('off')


  #sobel edge detection
  plt.subplot(2,2,2)
  plt.imshow(sobel,cmap='gray')
  plt.title('Sobel Edge Detection')
  plt.axis('off')

  #prewitt edge detection
  plt.subplot(2,2,3)
  plt.imshow(prewitt,cmap='gray')
  plt.title('Prewitt Edge Detection')
  plt.axis('off')


  #canny edge detection
  plt.subplot(2,2,4)
  plt.imshow(canny,cmap='gray')
  plt.title('Canny Edge Detection')
  plt.axis('off')

  plt.tight_layout()
  plt.show()

# read an image
img = cv2.imread('/content/img1.jpg',0)
if img is None:
  print("error:image not found.")
else:
  print("image loaded successfully.")


  #sobel operator
  #gradient in x and y direction
  sobel_x = cv2.Sobel(img,cv2.CV_64F,1,0,ksize=3)
  sobel_y = cv2.Sobel(img,cv2.CV_64F,0,1,ksize=3)

  #combine gradients
  sobel_combined = cv2.magnitude(sobel_x,sobel_y)

  #prewitt operator
  #define kernels (px,py)z
  kernelx = np.array([[1,1,1],[0,0,0],[-1,-1,-1]])
  kernely = np.array([[-1,0,1],[-1,0,1],[-1,0,1]])

  #apply kernels using filter 2D
  prewittx = cv2.filter2D(img,-1,kernelx)
  prewitty = cv2.filter2D(img,-1,kernely)
  prewitt_combined=prewittx+prewitty

  #canny edge detection
  #arguments: image,threshold1,threshold2
  canny_edges = cv2.Canny(img,100,200)

  #display results
  show_comparison(img,np.uint8(sobel_combined),(prewitt_combined),canny_edges)